name: SonarCloud Analysis

on:
  push:
    branches:
      - railway
  pull_request:
    branches:
      - railway

jobs:
  sonarcloud:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11

      - name: Build with Gradle
        run: ./gradlew build -x test

      - name: Run SonarCloud analysis
        uses: sonarsource/sonarcloud-github-action@railway
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
